version: '3'
services:
  supertest:
    build:
      context: ./backend
    env_file: ./backend/.env
    environment:
      - NODE_ENV=test
    volumes:
      - ./backend:/app
      - /app/node_modules
    entrypoint: ['npm', 'test']
volumes:
  test-db-volume:
